version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
executors:
  my-machine-executor:
    machine: true

commands:
  cypress-install:
    steps:
      - run:
          name: Install Cypress
          command: npm install


workflows:
  use-my-orb:
    jobs:
      # - cypress-run-project-a-job-1
      # - cypress-run-project-a-job-2

      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec cypress/e2e/integration/projectA/job1/*.cy.js
          install-browsers: true
