version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
executor: cypress/default

commands:
  cypress-install:
    steps:
      - run:
          name: Install Cypress
          command: npm install


workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome
          install-browsers: true
